export const ESCAPE_KEY = 'Escape';
export const ESC_KEY = 'Esc';
export const ESCAPE_CODE = 27;
export const DEFAULT_THEME = 'light';
export const ATTRIBUTE_THEME = 'data-theme';
export const STORAGE_THEME = 'theme';
export const STORAGE_WIDGET = 'widgets';
export const STORAGE_NOTES = 'notes';
export const REDIRECT_TO = '/dashboard';
export const HAS_WINDOW = typeof window !== 'undefined';
